name: SONATA
version: 2.8
date: 2015-07-29
description: |
    System of nearrings and their applications

authors:
    - name: Erhard Aichinger
      url: https://www.jku.at/institut-fuer-algebra/team/erhard-aichinger/
    - name: Franz Binder
      url: http://www.algebra.uni-linz.ac.at/~xbx/
    - name: Jürgen Ecker
      url: http://research.fh-ooe.at/en/staff/113
    - name: Peter Mayr
      url: https://www.colorado.edu/math/peter-mayr
    - name: Christof Nöbauer
   

maintainers:
    - name: Erhard Aichinger
      url: https://www.jku.at/institut-fuer-algebra/team/erhard-aichinger/
    - name: Peter Mayr
      url: https://www.colorado.edu/math/peter-mayr
      

GAP: ">=4.5"

suggested-pkgs:
    - name: "xgap"
      version: ">=0"
      url: "https://gap-packages.github.io/xgap"

www: https://gap-packages.github.io/sonata/
readme: README
packageinfo: https://gap-packages.github.io/sonata/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/sonata/releases/download/v2.8/sonata-2.8.tar.gz

abstract: |
    The <span class="pkgname">SONATA</span> package provides methods for     the construction and analysis of finite nearrings.

status: accepted
doc-html: htm/ref/chapters.htm
doc-pdf: doc/ref/manual.pdf
keywords: |
    near ring, endomorphism, Frobenius group, fixed point free automorphism.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>ABEMN15</span>]   <b class='BibAuthor'>Aichinger, E., Binder, F., Ecker, J., Mayr, P. and Nöbauer, C.</b>,
     <i class='BibTitle'>SONATA, System of nearrings and their applications,
             Version 2.8</i>
     (<span class='BibYear'>2015</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/sonata/">https://gap-packages.github.io/sonata/</a></span>.
    </p>
    

bibtex: |
    @misc{ SONATA2.8,
      author =           {Aichinger, E. and Binder, F. and Ecker, J. and Mayr, P. and N{\"o}bauer, C.},
      title =            {{SONATA}, System of nearrings and their applications, {V}ersion 2.8},
      month =            {Jul},
      year =             {2015},
      note =             {Refereed GAP package},
      howpublished =     {\href {https://gap-packages.github.io/sonata/} {\texttt{https://gap-packages.github.io/}\discretionary {}{}{}\texttt{sonata/}}},
      keywords =         {near ring; endomorphism; Frobenius group; fixed point free automorphism},
      printedkey =       {ABEMN15}
    }

