# SONATA, chapter 6
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("sonata04.tst");

# doc/ref/tfms.xml:22-27
gap> G := GTW4_2;
4/2
gap> t1 := EndoMappingByPositionList ( G, [1, 2, 4, 4] );
<mapping: 4/2 -> 4/2 >

# doc/ref/tfms.xml:36-45
gap> t2 := EndoMappingByFunction ( GTW8_2, g -> g^-1 );
<mapping: 8/2 -> 8/2 >
gap> IsGroupHomomorphism ( t2 );
true
gap> t3 := EndoMappingByFunction ( GTW6_2, g -> g^-1 );
<mapping: 6/2 -> 6/2 >
gap> IsGroupHomomorphism ( t3 );
false

# doc/ref/tfms.xml:59-70
gap> G1 := Group ((1,2,3), (1, 2));
Group([ (1,2,3), (1,2) ])
gap> G2 := Group ((2,3,4), (2, 3));
Group([ (2,3,4), (2,3) ])
gap> f1 := IsomorphismGroups ( G1, G2 );
[ (1,2,3), (1,2) ] -> [ (2,3,4), (2,3) ]
gap> f2 := IsomorphismGroups ( G2, G1 );
[ (2,3,4), (2,3) ] -> [ (1,2,3), (1,2) ]
gap> AsEndoMapping ( CompositionMapping ( f1, f2 ) );
<mapping: Group( [ (2,3,4), (2,3) ] ) -> Group( [ (2,3,4), (2,3) ] ) >

# doc/ref/tfms.xml:83-88
gap> m := IdentityEndoMapping ( GTW6_2 );
<mapping: 6/2 -> 6/2 >
gap> AsGroupGeneralMappingByImages ( m );
[ (1,2), (1,2,3) ] -> [ (1,2), (1,2,3) ]

# doc/ref/tfms.xml:96-99
gap> IsEndoMapping ( InnerAutomorphisms ( GTW6_2 ) [3] );
true

# doc/ref/tfms.xml:108-114
gap> AsList ( UnderlyingRelation ( IdentityEndoMapping ( Group ((1,2,3,4)) ) ) );
[ DirectProductElement( [ (), () ] ), 
  DirectProductElement( [ (1,2,3,4), (1,2,3,4) ] ), 
  DirectProductElement( [ (1,3)(2,4), (1,3)(2,4) ] ), 
  DirectProductElement( [ (1,4,3,2), (1,4,3,2) ] ) ]

# doc/ref/tfms.xml:122-130
gap> C3 := CyclicGroup (3);
<pc group of size 3 with 1 generator>
gap> m := ConstantEndoMapping (C3, AsSortedList (C3) [2]);
MappingByFunction( <pc group of size 3 with 1 generator>, <pc group of size 
3 with 1 generator>, function( x ) ... end )
gap> List (AsList (C3), x -> Image (m, x));
[ f1, f1, f1 ]

# doc/ref/tfms.xml:141-145
gap> IsIdentityEndoMapping (EndoMappingByFunction ( 
> AlternatingGroup ( [1..5] ), x -> x^31));
true

# doc/ref/tfms.xml:153-158
gap> C3 := CyclicGroup ( 3 );
<pc group of size 3 with 1 generator>
gap> IsConstantEndoMapping ( EndoMappingByFunction ( C3,  x -> x^3 ));
true

# doc/ref/tfms.xml:169-176
gap> G := Group ( (1,2,3), (1,2) );
Group([ (1,2,3), (1,2) ])
gap> IsDistributiveEndoMapping ( EndoMappingByFunction ( G, x -> x^3));
false
gap> IsDistributiveEndoMapping ( EndoMappingByFunction ( G, x -> x^7));
true

# doc/ref/tfms.xml:189-196
gap> t1 := ConstantEndoMapping ( GTW2_1, ());
MappingByFunction( 2/1, 2/1, function( x ) ... end )
gap> t2 := ConstantEndoMapping (GTW2_1, (1, 2));
MappingByFunction( 2/1, 2/1, function( x ) ... end )
gap> List ( AsList ( GTW2_1 ), x -> Image ( t1 * t2, x ));
[ (1,2), (1,2) ]

# doc/ref/tfms.xml:210-229
gap> G := SymmetricGroup ( 3 );
Sym( [ 1 .. 3 ] )
gap> invertingOnG := EndoMappingByFunction ( G, x -> x^-1 );
<mapping: SymmetricGroup( [ 1 .. 3 ] ) -> SymmetricGroup( [ 1 .. 3 ] ) >
gap> identityOnG := IdentityEndoMapping (G);
<mapping: SymmetricGroup( [ 1 .. 3 ] ) -> SymmetricGroup( [ 1 .. 3 ] ) >
gap> AsSortedList ( G );
[ (), (2,3), (1,2), (1,2,3), (1,3,2), (1,3) ]
gap> List ( AsSortedList (G), 
>              x -> Image ( identityOnG * invertingOnG, x ));
[ (), (2,3), (1,2), (1,3,2), (1,2,3), (1,3) ]
gap> List ( AsSortedList (G),
>              x -> Image ( identityOnG + invertingOnG, x ));
[ (), (), (), (), (), () ]
gap> IsIdentityEndoMapping ( - invertingOnG );
true
gap> - invertingOnG = identityOnG;
true

# doc/ref/tfms.xml:239-252
gap> G := SymmetricGroup ( 3 );
Sym( [ 1 .. 3 ] )
gap> m := ConstantEndoMapping (G, (1,2,3)) + IdentityEndoMapping( G );
MappingByFunction( Sym( [ 1 .. 3 ] ), Sym( [ 1 .. 3 ] ), function( g ) ... end\
 )
gap> PrintArray( GraphOfMapping( m ) );
[ [       (),  (1,2,3) ],
  [    (2,3),    (1,3) ],
  [    (1,3),    (1,2) ],
  [  (1,3,2),       () ],
  [  (1,2,3),  (1,3,2) ],
  [    (1,2),    (2,3) ] ]

# doc/ref/tfms.xml:260-269
gap> G := SymmetricGroup ( 3 );
Sym( [ 1 .. 3 ] )
gap> p := Random( PolynomialNearRing( G ) );
<mapping: SymmetricGroup( [ 1 .. 3 ] ) -> SymmetricGroup( [ 1 .. 3 ] ) >
gap> PrintAsTerm( p );
 - x - g2 + g1 - x - g1 - g2
gap> GeneratorsOfGroup( G );
[ (1,2,3), (1,2) ]

#
gap> STOP_TEST("sonata04.tst", 1);
