# SONATA, chapter 2
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("sonata01.tst");

# doc/ref/grpsupp.xml:32-55
gap> G := GTW6_2;               
6/2
gap> H := TWGroup( 4, 2 );
4/2
gap> D := DirectProduct( G, H );
Group([ (1,2), (1,2,3), (4,5), (6,7) ])
gap> IdTWGroup( D );
[ 24, 4 ]
gap> GroupList;
[ 2/1, 3/1, 4/1, 4/2, 5/1, 6/1, 6/2, 7/1, 8/1, 8/2, 8/3, 8/4, 8/5, 9/1, 9/2, 
  10/1, 10/2, 11/1, 12/1, 12/2, 12/3, 12/4, 12/5, 13/1, 14/1, 14/2, 15/1, 
  16/1, 16/2, 16/3, 16/4, 16/5, 16/6, 16/7, 16/8, 16/9, 16/10, 16/11, 16/12, 
  16/13, 16/14, 17/1, 18/1, 18/2, 18/3, 18/4, 18/5, 19/1, 20/1, 20/2, 20/3, 
  20/4, 20/5, 21/1, 21/2, 22/1, 22/2, 23/1, 24/1, 24/2, 24/3, 24/4, 24/5, 
  24/6, 24/7, 24/8, 24/9, 24/10, 24/11, 24/12, 24/13, 24/14, 24/15, 25/1, 
  25/2, 26/1, 26/2, 27/1, 27/2, 27/3, 27/4, 27/5, 28/1, 28/2, 28/3, 28/4, 
  29/1, 30/1, 30/2, 30/3, 30/4, 31/1, 32/1, 32/2, 32/3, 32/4, 32/5, 32/6, 
  32/7, 32/8, 32/9, 32/10, 32/11, 32/12, 32/13, 32/14, 32/15, 32/16, 32/17, 
  32/18, 32/19, 32/20, 32/21, 32/22, 32/23, 32/24, 32/25, 32/26, 32/27, 
  32/28, 32/29, 32/30, 32/31, 32/32, 32/33, 32/34, 32/35, 32/36, 32/37, 
  32/38, 32/39, 32/40, 32/41, 32/42, 32/43, 32/44, 32/45, 32/46, 32/47, 
  32/48, 32/49, 32/50, 32/51 ]

# doc/ref/grpsupp.xml:65-81
gap> G := GTW4_2;
4/2
gap> PrintTable( G );
Let:
g0 := ()
g1 := (3,4)
g2 := (1,2)
g3 := (1,2)(3,4)

   *  | g0  g1  g2  g3  
  --------------------
  g0  | g0  g1  g2  g3  
  g1  | g1  g0  g3  g2  
  g2  | g2  g3  g0  g1  
  g3  | g3  g2  g1  g0  

# doc/ref/grpsupp.xml:85-102
gap> G := GTW4_2;
4/2
gap> SetSymbols( G, ["(0,0)","(1,0)","(0,1)","(1,1)"] );
gap> PrintTable( G );
Let:
(0,0) := ()
(1,0) := (3,4)
(0,1) := (1,2)
(1,1) := (1,2)(3,4)

      *  | (0,0)  (1,0)  (0,1)  (1,1)  
  -----------------------------------
  (0,0)  | (0,0)  (1,0)  (0,1)  (1,1)  
  (1,0)  | (1,0)  (0,0)  (1,1)  (0,1)  
  (0,1)  | (0,1)  (1,1)  (0,0)  (1,0)  
  (1,1)  | (1,1)  (0,1)  (1,0)  (0,0)  

# doc/ref/grpsupp.xml:163-167
gap> InnerAutomorphisms( AlternatingGroup( 4 ) );
[ ^(), ^(1,4,3), ^(1,3,4), ^(1,2,4), ^(2,4,3), ^(1,4)(2,3), ^(1,3,2), 
  ^(1,2)(3,4), ^(2,3,4), ^(1,4,2), ^(1,3)(2,4), ^(1,2,3) ]

# doc/ref/grpsupp.xml:179-182
gap> IsIsomorphicGroup( SymmetricGroup( 4 ), GTW24_12 );
true

# doc/ref/grpsupp.xml:193-199
gap> Subgroups( TWGroup( 8, 4 ) );
[ Group(()), Group([ (1,3)(2,4) ]), Group([ (2,4) ]), Group([ (1,3) ]), 
  Group([ (1,2)(3,4) ]), Group([ (1,4)(2,3) ]), Group([ (1,3)(2,4), (2,4) ]), 
  Group([ (1,3)(2,4), (1,2,3,4) ]), Group([ (1,3)(2,4), (1,2)(3,4) ]), 
  Group([ (1,3)(2,4), (2,4), (1,2,3,4) ]) ]

# doc/ref/grpsupp.xml:211-214
gap> OneGeneratedNormalSubgroups( AlternatingGroup(4) );
[ Group([ (1,2)(3,4), (1,3)(2,4), (1,4)(2,3) ]) ]

# doc/ref/grpsupp.xml:228-240
gap> D12 := DihedralGroup( 12 );                                        
<pc group of size 12 with 3 generators>
gap> s := Subgroups( D12 );
[ Group([  ]), Group([ f1 ]), Group([ f1*f3^2 ]), Group([ f1*f3 ]), 
  Group([ f2*f3 ]), Group([ f1*f2 ]), Group([ f1*f2*f3^2 ]), 
  Group([ f1*f2*f3 ]), Group([ f3 ]), Group([ f1, f2*f3 ]), 
  Group([ f1*f3^2, f2*f3 ]), Group([ f1*f3, f2*f3 ]), Group([ f3, f1 ]), 
  Group([ f3, f2 ]), Group([ f3, f1*f2 ]), Group([ f3, f1, f2 ]) ]
gap> e := Endomorphisms( D12 );;                                        
gap> f := Filtered( s, sg -> IsInvariantUnderMaps( D12, sg, e ) );
[ Group([  ]), Group([ f3 ]), Group([ f3, f1, f2 ]) ]

# doc/ref/grpsupp.xml:257-260
gap> IsCharacteristicInParent( Centre( GTW16_11 ) );
true

# doc/ref/grpsupp.xml:270-277
gap> G := GTW6_2;
6/2
gap> S := Subgroup( G, [(1,2)] );                                
Group([ (1,2) ])
gap> IsFullinvariant( G, S );
false

# doc/ref/grpsupp.xml:286-289
gap> IsFullinvariantInParent( Centre( GTW16_11 ) );
true

# doc/ref/grpsupp.xml:302-309
gap> G := DihedralGroup( 16 );
<pc group of size 16 with 4 generators>
gap> C := Centre( G );
Group([ f4 ])
gap> RepresentativesModNormalSubgroup( G, C );
[ <identity> of ..., f1, f2, f3, f2*f3, f1*f2*f4, f1*f3*f4, f1*f2*f3*f4 ]

# doc/ref/grpsupp.xml:318-325
gap> G := DihedralGroup( 16 );
<pc group of size 16 with 4 generators>
gap> C := Centre( G );
Group([ f4 ])
gap> NontrivialRepresentativesModNormalSubgroup( G, C );
[ f1, f2, f3, f2*f3, f1*f2*f4, f1*f3*f4, f1*f2*f3*f4 ]

# doc/ref/grpsupp.xml:339-344
gap> ScottLength( GTW6_2 );    
2
gap> ScottLength( GTW16_11 );
4

#
gap> STOP_TEST("sonata01.tst", 1);
