# SONATA, chapter 7
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("sonata06.tst");

# doc/ref/ideals.xml:53-70
gap> n := LibraryNearRing( GTW8_4, 12 );
LibraryNearRing(8/4, 12)
gap> e := AsNearRingElement( n, (1,3)(2,4) );         
((1,3)(2,4))
gap> r := NearRingRightIdealByGenerators( n, [e] );
< nearring right ideal >
gap> l := NearRingLeftIdealByGenerators( n, [e] );
< nearring left ideal >
gap> i := NearRingIdealByGenerators( n, [e] );
< nearring ideal >
gap> r = i;
true
gap> l = i;
false
gap> l = r;
false

# doc/ref/ideals.xml:133-142
gap> NearRingIdeals( n );
[ < nearring ideal >, < nearring ideal >, < nearring ideal > ]
gap> NearRingRightIdeals( n );
[ < nearring right ideal >, < nearring right ideal >, 
  < nearring right ideal > ]
gap> NearRingLeftIdeals( n );
[ < nearring left ideal >, < nearring left ideal >, < nearring left ideal >, 
  < nearring left ideal > ]

# doc/ref/ideals.xml:175-190
gap> n := LibraryNearRing( GTW6_2, 39 );                      
LibraryNearRing(6/2, 39)
gap> e := Enumerator(n)[3];
((1,2))
gap> l := NearRingLeftIdealByGenerators( n, [e] );
< nearring left ideal >
gap> IsNRI( l );
true
gap> IsNearRingLeftIdeal( l );
true
gap> IsNearRingRightIdeal( l );
true
gap> l;
< nearring ideal >

# doc/ref/ideals.xml:224-234
gap> n := LibraryNearRing( GTW6_2, 39 );                    
LibraryNearRing(6/2, 39)
gap> s := Subgroups( GroupReduct( n ) );
[ Group(()), Group([ (2,3) ]), Group([ (1,3) ]), Group([ (1,2) ]), 
  Group([ (1,3,2) ]), Group([ (1,3,2), (2,3) ]) ]
gap> List( s, sg -> IsSubgroupNearRingLeftIdeal( n, sg ) );
[ true, false, false, false, true, true ]
gap> List( s, sg -> IsSubgroupNearRingRightIdeal( n, sg ) );
[ true, false, false, false, true, true ]

# doc/ref/ideals.xml:263-268
gap> n := LibraryNearRingWithOne( GTW27_2, 5 );
LibraryNearRingWithOne(27/2, 5)
gap> Filtered( NearRingIdeals( n ), IsMaximalNearRingIdeal );
[ < nearring ideal of size 9 > ]

# doc/ref/ideals.xml:477-483
gap> NumberLibraryNearRings( GTW4_2 );                         
23
gap> Filtered( AllLibraryNearRings( GTW4_2 ), IsSimpleNearRing );
[ LibraryNearRing(4/2, 3), LibraryNearRing(4/2, 16), LibraryNearRing(4/2, 17) 
 ]

# doc/ref/ideals.xml:504-523
gap> n := LibraryNearRing( GTW8_2, 2 );
LibraryNearRing(8/2, 2)
gap> e := AsNearRingElement( n, (1,2) );
((1,2))
gap> e in n;
true
gap> i := NearRingRightIdealByGenerators( n, [e] );
< nearring right ideal >
gap> Size(i);
4
gap> IsNearRingLeftIdeal( i );
true
gap> i;
< nearring ideal of size 4 >
gap> f := n/i;          
FactorNearRing( LibraryNearRing(8/2, 2), < nearring ideal of size 4 > )
gap> IdLibraryNearRing(f);
[ 2/1, 1 ]

#
gap> STOP_TEST("sonata06.tst", 1);
