# SONATA, chapter 11
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("sonata09.tst");

# doc/ref/nfplwd.xml:30-33
gap> IsPairOfDicksonNumbers( 5, 4 );
true

# doc/ref/nfplwd.xml:63-69
gap> DicksonNearFields( 5, 4 );
[ ExplicitMultiplicationNearRing ( <pc group of size 625 with 
    4 generators> , multiplication ), 
  ExplicitMultiplicationNearRing ( <pc group of size 625 with 
    4 generators> , multiplication ) ]

# doc/ref/nfplwd.xml:80-83
gap> NumberOfDicksonNearFields( 5, 4 );
2

# doc/ref/nfplwd.xml:99-103
gap> ExceptionalNearFields( 25 );
[ ExplicitMultiplicationNearRing ( <pc group of size 25 with 
    2 generators> , multiplication ) ]

# doc/ref/nfplwd.xml:116-132
gap> AllExceptionalNearFields();
[ ExplicitMultiplicationNearRing ( <pc group of size 25 with 
    2 generators> , multiplication ), 
  ExplicitMultiplicationNearRing ( <pc group of size 49 with 
    2 generators> , multiplication ), 
  ExplicitMultiplicationNearRing ( <pc group of size 121 with 
    2 generators> , multiplication ), 
  ExplicitMultiplicationNearRing ( <pc group of size 121 with 
    2 generators> , multiplication ), 
  ExplicitMultiplicationNearRing ( <pc group of size 529 with 
    2 generators> , multiplication ), 
  ExplicitMultiplicationNearRing ( <pc group of size 841 with 
    2 generators> , multiplication ), 
  ExplicitMultiplicationNearRing ( <pc group of size 3481 with 
    2 generators> , multiplication ) ]

# doc/ref/nfplwd.xml:159-171
gap> C7 := CyclicGroup( 7 );;
gap> i := GroupHomomorphismByFunction( C7, C7, x -> x^-1 );;
gap> phi := Group( i );;
gap> orbs := Orbits( phi, C7 );
[ [ <identity> of ... ], [ f1, f1^6 ], [ f1^2, f1^5 ], [ f1^3, f1^4 ] ]
gap> # choose reps from the orbits 
gap> reps := [orbs[2][1], orbs[3][2]];
[ f1, f1^5 ]
gap> n := PlanarNearRing( C7, phi, reps );
ExplicitMultiplicationNearRing ( <pc group of size 7 with 
1 generator> , multiplication )

# doc/ref/nfplwd.xml:189-199
gap> C7 := CyclicGroup( 7 );;
gap> i := GroupHomomorphismByFunction( C7, C7, x -> x^-1 );;
gap> phi := Group( i );;
gap> reps := OrbitRepresentativesForPlanarNearRing( C7, phi, 2 );
[ [ f1, f1^2 ], [ f1, f1^5 ] ]
gap> n1 := PlanarNearRing( C7, phi, reps[1] );;
gap> n2 := PlanarNearRing( C7, phi, reps[2] );;
gap> IsIsomorphicNearRing( n1, n2 );
false

# doc/ref/nfplwd.xml:242-263
gap> C9 := CyclicGroup( 9 );;
gap> psi := GroupHomomorphismByFunction( C9, C9, x -> x^3 );;
gap> Image( psi );
Group([ f2, <identity> of ... ])
gap> Image( psi ) = Kernel( psi );
true
gap> a := GroupHomomorphismByFunction( C9, C9, x -> x^4 );;
gap> phi := Group( a );;
gap> Size( phi );
3
gap> orbs := Orbits( phi, C9 );
[ [ <identity> of ... ], [ f1, f1*f2, f1*f2^2 ], [ f2 ], 
  [ f1^2, f1^2*f2^2, f1^2*f2 ], [ f2^2 ] ]
gap> # choose reps from the orbits outside of Image( psi )
gap> im := Image( psi );;
gap> reps := List( Filtered( orbs, o -> not o[1] in im ), o -> o[1] );
[ f1, f1^2 ]
gap> n := WdNearRing( C9, psi, phi, reps );
ExplicitMultiplicationNearRing ( <pc group of size 9 with 
2 generators> , multiplication )

#
gap> STOP_TEST("sonata09.tst", 1);
